version: '3'

services:
  # redis-log:
  #   image: redis:7
  #   restart: 'no'
  #   volumes:
  #     - /var/log/docker/api.user.tax/redis:/log
  #     - ./data/redis:/data
  #   entrypoint: chown -R redis:redis /log /data
  redis:
    image: redis:7
    restart: always
    # depends_on:
    # - redis-log
    command: redis-server /etc/redis/redis.conf
    volumes:
      - ./data/redis:/data
      # - /var/log/docker/api.user.tax/redis:/log
      - ./Dockerfile/redis/redis.conf:/etc/redis/redis.conf
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
  pg-log:
    image: postgres:15rc2-alpine
    volumes:
      - /var/log/docker/api.user.tax/pg:/log
    restart: 'no'
    entrypoint: chown -R postgres:postgres /log
  pg:
    image: postgres:15rc2-alpine
    volumes:
      - ./data/pg:/var/lib/postgresql/data
      - /var/log/docker/api.user.tax/pg:/log
    restart: always
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USER}
      PGPORT: ${PG_PORT}
    depends_on:
      - pg-log
    ports:
      - ${PG_PORT}:${PG_PORT}
    command: >
      postgres -c logging_collector=on -c log_destination=stderr -c log_directory=/log -c log_filename=pg.log -c wal_compression=zstd -c default_toast_compression=lz4
  # api:
  #   build: ./Dockerfile/api.user.tax
  #   restart: always
  #   depends_on:
  #     - pg
  #     - redis
  #   environment:
  #     NODE_ENV: ${NODE_ENV}
  #     PG_HOST: ${PG_HOST}
  #     PG_DB: ${PG_DB}
  #     PG_USER: ${PG_USER}
  #     PG_PORT: ${PG_PORT}
  #     PG_POOL_CONN: ${PG_POOL_CONN}
  #     PG_SSL: ${PG_SSL}
  #     PG_PASSWORD: ${PG_PASSWORD}
  #     LOG_HOST: ${LOG_HOST}
  #     LOG_DB: ${LOG_DB}
  #     LOG_USER: ${LOG_USER}
  #     LOG_PORT: ${LOG_PORT}
  #     LOG_POOL_CONN: ${LOG_POOL_CONN}
  #     LOG_PASSWORD: ${LOG_PASSWORD}
  #     REDIS_DB: ${REDIS_DB}
  #     REDIS_USER: ${REDIS_USER}
  #     REDIS_PASSWORD: ${REDIS_PASSWORD}
  #     REDIS_HOST: ${REDIS_HOST}
  #     REDIS_PORT: ${REDIS_PORT}
  #     SMTP_HOST: ${SMTP_HOST}
  #     SMTP_PORT: ${SMTP_PORT}
  #     SMTP_TLS: ${SMTP_TLS}
  #     SMTP_USER: ${SMTP_USER}
  #     SMTP_PASSWORD: ${SMTP_PASSWORD}
  #     SMTP_NAME: ${SMTP_NAME}
  #     API_PORT: ${API_PORT}
  #     API_HTTPS: ${API_HTTPS}
  #     CPU_NUM: ${CPU_NUM}
  #   volumes:
  #     - ./api:/api
  #   links:
  #     - pg:pg
  #     - redis:redis
  #   ports:
  #     - ${API_PORT}:${API_PORT}
  #     - ${API_HTTPS}:${API_HTTPS}
