version: '3'

services:
  redis-acl:
    image: usertax/redis
    restart: 'no'
    volumes:
      # - /var/log/docker/api.user.tax/redis:/log
      - ./data/redis:/data
    entrypoint: >
      sh -c "touch /data/acl && chown -R redis:redis /data"
  redis:
    image:  usertax/redis
    restart: always
    environment:
      REDIS_DATA_DIR: /data
      REDIS_ARGS: >
        --aclfile /data/acl --appendonly yes --bind 0.0.0.0 --port ${REDIS_PORT} --save 64 1 --save 32 8 --save 2 32768 --repl-backlog-size 256m
    volumes:
      # - /var/log/docker/api.user.tax/redis:/log
      - ./data/redis:/data
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    depends_on:
      - redis-acl
  pg-log:
    image: usertax/postgres
    volumes:
      - /var/log/docker/api.user.tax/pg:/log
    restart: 'no'
    entrypoint: chown -R postgres:postgres /log
  pg:
    image: usertax/postgres
    volumes:
      - ./data/pg:/var/lib/postgresql/data
      - /var/log/docker/api.user.tax/pg:/log
    restart: always
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USER}
      PGPORT: ${PG_PORT}
    depends_on:
      - pg-log
    ports:
      - ${PG_PORT}:${PG_PORT}
    command: >
      postgres -c min_wal_size=1GB -c max_wal_size=8GB -c max_worker_processes=10 -c max_parallel_workers=10 -c max_connections=128 -c effective_io_concurrency=256 -c random_page_cost=1.1 -c maintenance_work_mem=128MB -c checkpoint_completion_target=0.9 -c shared_buffers=512MB -c effective_cache_size=1536MB -c logging_collector=on -c log_destination=stderr -c log_directory=/log -c log_filename=pg.log -c wal_compression=zstd -c default_toast_compression=lz4 -c wal_level=logical
