version: '3'

services:
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGPASSFILE: /var/lib/pgadmin/pgpass
      PGADMIN_CONFIG_SERVER_MODE: "True"
    volumes:
      - ./pgadmin/pgadmin/servers.json:/pgadmin4/servers.json
      - ./pgadmin/config_local.py:/pgadmin4/config_local.py
      - ./pgadmin/pgadmin/pgpass:/pgpass
      - /var/log/docker/admin/pgadmin:/var/log
      - /tmp/docker/admin/pgadmin:/tmp 
    ports:
      - 8800:80
    entrypoint: >
      /bin/sh -c "
      cp /pgpass /var/lib/pgadmin/pgpass;
      chmod 600 /var/lib/pgadmin/pgpass;
      exec /entrypoint.sh
      " 

